[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "a1c55ca6b2515b5830aa22d2bd69111b973b3821"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "49e225d6bcd452067690ec8269b0556f41f0b9a6e7c705f3388dd24457ca1b15"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.x86_64-apple-darwin14.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "2179feeb4252a055f4978d1455d754b864fb25c3"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "75ad000d57af7b8d35a4b14dc78c9179c9cd438de0ba016904bb199c88453d19"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "17c889ba2dfc14b7987994254d23963d92b3857d"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "4886150887d79ef639f11953fc840a94052ca3053c80d1df086777ffb49514e4"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.x86_64-unknown-freebsd11.1.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "3cf34c787b5b6de1cfd4bfdbfebd9ea9cde2798f"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "54975474047ba6b6761eabba47a3cdb62ab1d8e8214ae5a37656e6ea7ab34514"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "11cb93b06d2b5a69fefc12015b0b9bb2d61ef921"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "58bf4012dc976e3830ca67b61c175b7be0a8c84b4d401ae095ca7b3ccf1960ae"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "ddc89cddf8822f53a219dd6ff2afc2e8fef0f7b1"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "cfa537ad506201c048b66d1557a4b2387c90ed6079624946fcc75ae292c30e1c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "0a0f8263b8f7a900539ee2be800ac66a5d86a237"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "1728b095f9e62030c79d27bc8977c05f89651eea89c8c0cf5e94f27013cada9c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.x86_64-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "0e70a92ecb0c17dcee22d788ad7eb4dd1a23ebbd"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b208d928988f0d11e66f698cfa579c86b883f949a6341e21aec4dc8b388850dd"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "1d441609fcb8f895b3dc8d877d56d029a6d52e20"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "4e11b3bdd7aec6f977d48d8ae806d72959afd81aaf76b69ef73744c30c2b32d8"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.arm-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "97cd562feb368130a948e632aaa4d4f0d53c94ff"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "bd0864cef7e7ca26a9b83316004c7634855e082f21b003c10abe5023dcaafb82"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "ac46e075a896fcac29769dd107ae4b1f8a0ce631"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "1ec69a2ddb95fa3a5d7f5260bee06b9d090227bda0c876cd4bceba3bd5265871"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.arm-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "0f9ca4854d23eaefbc28f6fa3c3792299aa6fa20"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "77c474f69525b0d292c35aa52e0d9d9b0dfeade3cc87c5037cda4ce0837c8844"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "4747eb17cc41709fad517de2ceba653977c8819b"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "30dde5a142c8e6b90842e57066d80d467b9906432a8dfa30521f2d8b1783615d"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+3/gdk_pixbuf.v2.38.2.i686-w64-mingw32.tar.gz"
