[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "53f6bc4a6b75269570ac63b31606cbe37a82825c"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "3c395778e06e0e791cfbffd878fc2d8d9864290e0a57f7ee6d0a93ab66d962b9"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.aarch64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "3d667b315873e1b04f7c29619eab8b448d05e17c"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "dce55110112dfcbe2579c78a3a46948e05427fc846ee1690da7545a3f086052e"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "28edb3fbadfdb9650b942a1c340b85a8b049a5c6"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "2c3aed5f56c9336eeda66f15d6f125d4dd293a7bf06c452d4e7a080a6180b841"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "852c673f5837677ae07caa92ae440d955df2a45f"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "598fbee9fcd658a95e7df1a89a32230c083ed44fa197e8f878105edaa5917b40"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.armv6l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "790ea7fdc9ec72b28bb4544636a1cf07f739c18a"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "dc135bf3a038011d4e0da1081c1a5016dec83aae5026003bf36920a7bbfaa570"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.armv6l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dcc5177bd4e2de6808ba3d3da8be193bf4c73a43"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "ad4c3bccdca21ae1fafb3aa1188594e97b98af673133f53af66226f17a971461"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.armv7l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87b663f1b7f91f2bbd3b09241479fec6ed52292a"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "4147575f452e19643eeaec37b5e4d27caca7915fbf6a730b6db585ea64595b9b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.armv7l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "0d2aae0ad83dbdf190b9850509c76776fdfabe9e"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "936b4868aeb052bcf11d3169788c512b7a1923492ebcb738e45003c1890da2ce"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "5702ea2c771d25422066bcbe3d8ef4e562050067"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b7b5df91a769d814826d2ec0dfb0de6c7c56cdfe725eebcf1374ba1ea7a3160b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "6527fdffad1a2dd5e9604e9b1ef0096c9d5d105a"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "e83023912d658fcd33cc3786c2ca16ef4a67c0be051befd66b6a7c0548d03118"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.i686-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "d8dd8f760092c2edd8620209d5584bab66b1c7e7"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a22d5d8d6e2cf72fbc9305b500021e541f8c58bf5094478f41c2b07b54f1226b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "848362f962b370c5ea57b51e158b03e2a5cc39ed"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "ae7366ced5f1f84e27bc29bc1de1e6b98a77434ad3879f4b955ab86dbc8aa78d"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.x86_64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "a33d033f5fbc379a9949901f0442eb469fb36d14"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a2eaf2de3f1bac8f5a0bb96a82f1b155c230f1c36bd279a112a8c6aeb03125e6"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "cad4c865a3e9b7f02353cdf9917771df8a7cae49"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "249cc0a0c2453ca136e2943a7632fb9b9af59eaa594a5423853b93981783b958"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "395c7cabfb06653cf5bb6cb3e16f6a12b2aa5d60"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "b61646935e11c2a8c9bf08b81f126734f4b1efcab7e9527c2460ec4d9889d0b4"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.x86_64-unknown-freebsd.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "8455e1b01c79801f7aa4474ef4cf035f678ddf65"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "ceb7df2622e231c40931aa712e78d69f72864867385962b91d3845dddc7ad614"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.10+0/gdk_pixbuf.v2.42.10.x86_64-w64-mingw32.tar.gz"
