[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "5a070eb2834af0c3be81233eb92d42f112c84242"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "0695b85ff92e75c56d77675282d1733f0cca881b9f42739b6d928e4b9cb9e9c8"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-apple-darwin14.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "062d03ed4e287d14b8da7cc395d20c62d2538d88"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "f2b96990f2f0801a8bd01dd1a73c85573eb5eb3f03cab58d88bc2b98d89f54e4"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "d83dc801a66fb237888c96a2b45bb4f3d3582d72"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "85c90fa117808fe17350eb64a3b4b56d39a1c0674065d3ad09bbc0ed0e83b54a"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-unknown-freebsd11.1.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "73bf8024eac65082a5f4894de866c3d50c1a3ad1"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a3837e94b5f82091ef40c3215653dfd81d2e55d88ab635b6ee4767d9f8fb5e8d"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "4fec1dfa82f2daf7934f9de2cefb7d7b9032bce1"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "e9e5e3bf2049ef049e3b7116b69e4021571777261c1b9530321f81b63550f200"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "c8179ebc7b9bbf8b033db19698cff66de594f681"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "63a743e3928082655d2620c45f2ceac762d822e1bf4fcc314a396e3c1bcff640"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "d3c16f269e5b318adf8a688dfb0cf78e31948827"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "32c7504414d1c9cad607982593af8ea36765f950b03517391b789e265148d7ba"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "308a86deb450ab922c7ee072e5f9be0f6089dec8"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "1165bbc1525c1ccc5125fcc3448da68611e893a4a1ee1d615113f31e413aa904"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "19a37bfb2de05ab4ca29931e2b07cff8a6377e5a"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "964da006b41ee59686500746276708eddb34f8d639da52068e35cfc2911b9171"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.arm-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "63c9172082e698a932aa41da4228d1a0b87ed84a"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "2b46b3b9cc7b1fa5effb6833e7289d4b54506feaf4741896d343c6f9c19e2804"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "9e354a98336a705ced3e6601a2d6f8cbea14dfc3"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "2fae09c3203e1af2220c8df4b2fa6d52b4a4a27a8d2be0a21da1c6748b2c9675"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.arm-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "97a0c2f8e9d01f19997b964d0618020d9db1cdf1"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "d9986367bd4b2800187054530949abb92a874ec43922f354c7e73965abfa3b82"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "3c5d9c56fa4baf6c1e32d6e6a3f1213f7c7eff9e"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "043407ca19790166318cecc8547fe9da9ac9a62116889a2a743d346cc1cf5a6e"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.i686-w64-mingw32.tar.gz"
