[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "db0f0d61025373ea75a6d9a6c0b981787a9e9654"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "e7c5c3a7b2382643fd89432ad6835f8a29473a212e043c3f368997803aef52df"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "fba8fac90b778d9046ed553e5f4c5ec4f5bee364"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "97588ef84d471b8bba7a5564b076a9e93b16fa6466331bb2ff1f742463733d89"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "7e6c218436a16a439cf586c8d68f0af2e384fe1a"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a9c0bd89e5c9bfd5f17ef32922ac9a064e1f2a98f680570355f7eb0af648959c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.armv7l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "c5fcc77cab9f83e795b35fc2c848232ae1af11fc"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "5c7c8ca47c691e975506c56649266c79670bdf19ff4dcf38b22d59f1f832159f"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.armv7l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "083e36f6a8e5cf873beec21a893562aab0d88e43"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "89dc93eea73c6832e75b585820f7db59bf750c8b922cfdfc40750cb082fb8389"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "6d371a5795087bec580b2b6069b947202f519f24"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "69fbe88ad4ca406e55fb4727feca160b67db461e315f0ae82e8b776f972b3d3f"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "ff6da04f9b908918088b76403401ffa3a7a59ab0"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "2cea07dfd49fe02fd379cbf338b18bb212a4ada98976f9ee411bb0824e8e3e4e"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.i686-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "debefd33cec1869c018bf7b6927d36ddde480ea3"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "6403c610be4288dbd622eac49824087a05baac217f01358144083ea4dd233a31"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "18f5e111532098d4d6cea888fdcd8105c5437a6c"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "9dcbeb87a5f9315244f7e7bb758d537d49cd463392b03d18187a563a55f387a6"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.x86_64-apple-darwin14.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "5bb85fec039cf382b8981c1c064dd39c00ef8c63"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "3a83845ffca354ea872fff3f1d25d11f85715e2e0f017ae718b5d00bb7db60a3"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "ec47cd2fe867f408f2e22cbd9bd4251925906af2"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "edf14140a02417d01519115ea34ae2759b6d52488ca435f0f2bc1c3cc7b29bdd"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "06ce7b71cb01d2439e0e144e052ee362821ef037"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "11fc264f599bc7c8022ffe1b8a8cbc8b0fdb46ce5f7209072b2f5bd1708d4710"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.x86_64-unknown-freebsd11.1.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "179a37e0866df1da476dc33f034f03dc4fb3ed1b"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "005e2d1935926eb4a777ab483b84998b5da258960be5c5266f3ff99e0b7bb624"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+7/gdk_pixbuf.v2.38.2.x86_64-w64-mingw32.tar.gz"
