[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "483811ec730a8573ed4ee19bcaf61462bd19d9fe"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "35559c1bf63f880c0faec5422c9adb8d8e7a0a9de02e9da4ee54ecec0f969dc6"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.aarch64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "ed3bafb194e53c387cfd89cdbfb3ccabec70c812"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "cff74aab983a9f35aaa67dd0e20ca67afac495671873a0406da6328984c507c3"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "29a2859f170f992de4f681ab6b19fb8eee4c5d5a"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "2bc7056258b0acda7e90386c59e92d776614cb0d4ade4035701e6b71dd9df727"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ffaed8721a9e46cf5886216110a48e475c64874"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "f8757bc645119cbcd0de2394d41b7e359f8c227977277f115b8168cb8ff02c80"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.armv6l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff479b4d48049b80046c12f713f40688e0c370a6"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "3d0590b7fca3aabff1cb9a3740f9a296e3c70bc310caf0f0fee423fbf20fb15d"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.armv6l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f1be0fad54492bb77a301279775a6b5c3ff39fe2"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "911603ed0136a556da999d410bcf92ca5806ce33eb6a05586339b26c407250d8"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.armv7l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5af48e78c33ff5cd40dbeb63de58bfaa9f0f732b"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b35367962da0cc92e03ce2a070227fd7c104c6e8225307cdc5a57a047a4cf751"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.armv7l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "b4aa41be09905b8e1055f0e4703969c3bac1cbaf"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "460e00f9031077d8abb3803df2349bc9e432f0204c66242014bca9437caf33d9"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "5887721856bdcc8bde72085b03f1be7cac988fb0"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "2eb86615157c6d25b03d803f5a2ca6418eff3af1227129ae0490359013114b2e"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "80749168fd43cc3186fdbb26baa9c6f23afa73a7"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "e00a9483d0ddb592cb173a36aa40ccf454d88559857f2bf0272e84531518b704"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.i686-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "05186b4ee76cca69750781e0aeab6a1dc38ffbd6"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "622047c355c2903265ac916b48145b47365630a71dab9f0da551eadce0e468d9"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "3513d4464ff720f5788cb3c16be8b3079657e341"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "e0bf0881bc6f806cde11f725a6cbebe05ee0ba7142494dd8ce197b3f1f629ff1"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.x86_64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "95045289183d1ae3c119c957404678bfa2dc8ed2"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "4efbd660a2e85dbe93ef55d939e593df72ce90da39a2b42f46f6dd9a90bc6470"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "e023228613fd39e31c01541e19bbe6e2019ceb46"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "99310f6ad7800c20de3ca052a7eecc1fa7d283961e2592d5b2d69c8baee37673"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "53e1d3ad75a3d55230d4f31f22d648ffe9184583"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "11f2ae71ec29a2af19c148cd78dfb14af08ec831868ca383454b5d1a47dbefac"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.x86_64-unknown-freebsd.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "57bd9311faafa3d8e73dfb991c2cb420f2c65ab9"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "b5439ade7e680805b0e89b8d88641a5f75ae6ebe5b2fe14ccf89325e49c9e7bf"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.8+0/gdk_pixbuf.v2.42.8.x86_64-w64-mingw32.tar.gz"
