[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "011ca479ecf25884458b6e11b7ff0b9f0bb2417d"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "1ed6d14392ab729f2818c6902be222a0064be784efdd0b604d5e1ceb37b20e99"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-apple-darwin14.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "aae099f88bc025b31ca878b129e613bebad4318e"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "510c4086719e7fa988bd9c14bdb8f2c4949c0895d7960a6567c1370fbdbed92a"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "d41f26390e362bc4a0d5d8c1135d264d4764b3af"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "34e3d3d6beea713c334386d8e579556804fc5de4ad894e8cc26a8abe3149b218"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-unknown-freebsd11.1.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "1f31ae38eeacf9e8648ef509a882e03687dc83ec"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "23175071ca92a8e149b03b61821cdaa3bfd0d30efb0360ef97f4a5f444687cee"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "eb27fe4a0ca2ec5d410cf91eb9e859b9447e0e4d"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "9a600e3a757c67547d1a5ac23f5f82c30c1e8aa8772762d780604a0b433d3d8d"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "b2c4354a09db8324dc406cf88495a4a3c6459a89"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b61aa42993ef808e3122784d9ffb4e47d36667d126d5cc2c965938413f5ae01e"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "b398dee16b1d30850cf6d543b1a18174314e5db4"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "10df782bd86ddda102b3a45078500eb442dea174c9c2eb754188a5f4d8828eb9"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.x86_64-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "d11a862249455d55bd6777f0f7aa4af212d1ffd3"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "37bcfac4448059821c3a6066e62dcb9720a67b556837c34abc9a4fe6504ab575"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "bfb67ff6f0e48fc4f1316ad7986855fb3cf6a4e6"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b38121d5a85e1f64706f7115e76db9fe6268340c198eea1cbcf0b1160a852a3a"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.arm-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "fc3948f1227b5fefe6bccb1d3dc1f3a618ab49df"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a01965adb281c4c14447f75ec3bfeb09da8ea14194e87e501cc902708ded1a40"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "095ed4bcccc6d8684362bbad7bf9b67a26b62f76"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "40b0b565a9ce1a4e61559bf94faa1912f9e833657da32718e75bf094da6da483"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.arm-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "87e126794eb6e8d2f69a283e7ce0a3873ad6c70f"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "6f257c0eac634fff5afd79ea554f5bb14d2c532d140e3e5b463122eceff1e918"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "6f9247b362865faab9cb6ce02bb87996080abd40"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "1295653ebbfe14951123dad4b525a5b0bb78613766466fdf286a08946b418f5f"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+2/gdk_pixbuf.v2.38.2.i686-w64-mingw32.tar.gz"
