[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "ba88ad1671e65c47692fd088cd2106b0097c6664"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "edeb8aaad9e64f99f31a3fd46131d52a6b77a5ddf9d4403a90ebd056cb3b2d57"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.aarch64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "2f9c39ca0c15fabe0884248f96ab1f1fad37d718"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "45494817a1f08c2a58b8e2ec681f726a119b538f4279bfe6ca98de3c3c4fe39c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "2ce570478486a1c67dc03ac0a1d302bb32b1b13e"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "4dec58a18e283784174a5a15d93896e59ac9f1e0046d41b6222308a958b9be5b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "0cd60a3053f94f37deaa1fc0882302db3181849b"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "413d68026e5d48c5c4f57d7233cab9faec16364d8150bc63b742e2e84d4fcd2e"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.aarch64-unknown-freebsd.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a284f911905b19b321b17cbf44209344470c2f23"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "a2f6fcbc63ee6671ca5551187d83e4056b69b6cb3972f5057c5090a362fe1c7a"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.armv6l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9189a05b33c31ed01eb4f79067ec565e963caaa5"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "5a513e500a9329e0703cfe9f088a0657df2e5a2644722f269b2dd597ab28e472"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.armv6l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fffb099faca7010c3f1014c8a7679d2e74d3a51e"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "7150c6fbfd8de475026ec9061f3c64796c8d2368125bd39681da796c16e7c443"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.armv7l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "858137f1c7f4ac2cd19700a44aa960151bc61894"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "41b374837f28a5d448623b6f4327b39df208f67c3e88f64d92c4dea767bf5285"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.armv7l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "16400c7730ddc98f9e444dd799f8d43b6be93608"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "229d4c222807eea820ec84cbdfbe615bfe2046690c123a8fc0637b36a7d74027"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "361295f923590f8237421f8dd40b15754d44677f"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "6817cba78da469af5eac846f20e90fd488616f44e2a3b2a093b8794f5c359da3"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "28fabaa8f2a8f7562d93875ea37229b6b1d298d3"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "3bb0e5f809c136b2163efab02354f648301058e853ee61b9150368cd0ffb7cac"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.i686-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "3aeb6a535bd531cb4a5e697183001c1ce6579847"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "b093d0254d23b25dbbb068213df59704d16d0dd3d21a28c5ea5b51dcc3dac375"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "ec59318bf6ba3a50a680b9e3af81c514d48686b0"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "e7404d1977e1b22ac971068a0930e09887e805a7b5eb611d5f6add64ee73038b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.x86_64-apple-darwin.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "d749e4294fe1cee4adb85503910b8343baf55223"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "df600b6e7ee387ad0cfefdf9be80873d652f780382eb9c3aef93d901d0f61be1"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "a19272562b96516bc3172cf5e10ad2b9a7bfb96c"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "86070a7708c52669744d47fe315a876cc7469875a0c4ac039dd2fe88a62e70c0"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "dd5d6cb82c814dea9931cc7c1ab4e8f2f4b32eb1"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "14f6c1b3cb3cd664fd7bb9f39d9df53fd5768713b1bbed00724d1ad9050d2b73"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.x86_64-unknown-freebsd.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "d45af30c75a1e58a90aaca19dc432dac46405245"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "ba929052086000602b1aad872d3b2020a71a83bf7e85be38b63e893cc464d196"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.42.12+0/gdk_pixbuf.v2.42.12.x86_64-w64-mingw32.tar.gz"
