[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "5e011cc179697d71eb4b92e60779deced7b8d0ff"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "170e005275f74bb2c5ce0fad38b57c58e23748017067b5f8bd8be22ab271984f"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "d343450eb0ad71203db0ed64bf798a0c21493885"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "579d4d8e85e78588899de645a0e3ae31ece29416cd6e27e0a38579ceceed66e1"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "5d1f5df530b677d44f1041df9360e90bd616e840"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "ead277978cf05eb6db19a557b77666422463ed3d9bc91aaf233a758b8daef4f4"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.armv7l-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "2a420d5ec67bc64f1804b05ecf7bc35989b3b600"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "34fc1036800b813a721c88f28b11612cdfb33d0668f0e698218351b87f5622b7"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.armv7l-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "ed9fcc3175c52834595a98a5a7fd4aef9fd57c11"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "3cf1dea890565be465f29a9cf991f35d5cea5e3351b1555dcb1b2211b5e3b1ac"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "c78ac430d56754535a02bfcdd48c1dee010a69ba"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "389d5cdace358d07c076cf78370e54a53cc7b2a35c488448b904598bf1fc3392"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "cea0ed2cd8b5be9b961e534b33ee8bb7ddc2d0d9"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "ca325f2cc0dacc684bf87b9fbd1ad30e800e74140260c28756ea43e02c503b21"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.i686-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "045fba00e03bfac287861d051d48d0b59fb9eca5"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "aeb81e9d3ee433714ea6656789e5424be7df06ab72b88deb47da1f831c4d8b76"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "20a5fb667ea10e12aa4e69e4c403840115da4f90"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "d5ad0a4237a701a087d0eec6a1457af0cd8fa25b38431de424d9169b42435655"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.x86_64-apple-darwin14.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "575e03c4bfc127b25d9a838226e2271a8efec3ba"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "8170b5121717513cc8b887496394010f7cf647c88fb341c82d215b32cdf35d0a"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "508b62a3812ba473be95bdb71edb386b4f58b588"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "cc1f30b01f2a88863df5aff54f531fe5111a9402f7e4790c0e7d3db8d24e4a15"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "a498ab623bff7286fe7fd9db908d26978564f3d9"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "de1c6848d3fc998ace6fb84ad7768bdd96660eb7dabf57eb2d3946de322dd139"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.x86_64-unknown-freebsd11.1.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "6a02a87a3bb9925d53326247ced99fa45971df45"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "d199544ff719593c21d8c3261f441a9ee80605d55ca962d9148fc6093b0282c7"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+8/gdk_pixbuf.v2.38.2.x86_64-w64-mingw32.tar.gz"
