[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "841aa786db0ce82f1d07f9291474e2bd73abff11"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "86117b98b06c8aac8d234592b986f9c09eec6008d7c427bbbc076ce49ee4ef5b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.x86_64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "0b47c721292ecfcbec87a20f2464ef4a506ddb87"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "353f4ea049aaff1c357532feb2fa10a79ad8e66ccc64c6cff94d9e545762d038"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.x86_64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "1b40640691eed27b346a431c371e6db9ed0d7fd6"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "34105933c10c85e7c6075689afc2e09ed92e4341c2a0a607d758ea415ef8dd56"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.aarch64-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "291c528c4764c258ca024d39f3ea25af38e0733c"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "2c63d92706e7009bb2f8ba07da0acb389dcad354fc5e4a55b98ff7d00626f84e"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.arm-linux-gnueabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "9da7aa630b6645ccbbc083ba038a1e1adebdfe90"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "369558716c9841bc9339b2294911daede390dcb748799996cad1f86bde3d4d38"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.i686-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "d19ee3bf9a86514179d34b86d6db58bcc0bdb953"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "c3752174ece81527ec584145f40f3ebff7371f77292ee3674dcb3217e759fe27"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.i686-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "aarch64"
git-tree-sha1 = "03bba62050b4d6b0d1bab13d14463a554ff2594c"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "8749909ceb2979899fc99406bc0e8e1d36b64c3746b0650fc60e58bb9fc49f5c"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.aarch64-linux-musl.tar.gz"
[[gdk_pixbuf]]
arch = "armv7l"
git-tree-sha1 = "d818159538188bc561ff929ffd30ccd4d6e96e80"
libc = "musl"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "479195af5f22294095430968f61644001b6c87e2bf016f638d717b8ad6ece6d6"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.arm-linux-musleabihf.tar.gz"
[[gdk_pixbuf]]
arch = "i686"
git-tree-sha1 = "e5d87021a41ed23e9da4b30abb7f42fd4a7fb89f"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "87fd2bfb6ad922d198ddb01b50203ec649e330113bbbfe8af4274bb0065bda99"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.i686-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "powerpc64le"
git-tree-sha1 = "8334606467eaadcb5fc47ab7b78d8fd4f2d67a99"
libc = "glibc"
os = "linux"

    [[gdk_pixbuf.download]]
    sha256 = "affa33f78e7d62766678436373c56f1384e04d6fa1afc87436e3d884f694b46f"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.powerpc64le-linux-gnu.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "fc0cdfdfd7a489451f7f997e6a1adaa21a440425"
os = "windows"

    [[gdk_pixbuf.download]]
    sha256 = "09c2a7c2803f4d9b42f79f8dfc6fffd2b0bc358d7ac1bf39f12026f73985747b"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.x86_64-w64-mingw32.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "c90b26be37c10aaa5325684534094965422f039a"
os = "macos"

    [[gdk_pixbuf.download]]
    sha256 = "699e71eb033e2629d5356026cd9e9abe81816d7c4092eeaddd88eb97092113c5"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.x86_64-apple-darwin14.tar.gz"
[[gdk_pixbuf]]
arch = "x86_64"
git-tree-sha1 = "2d8e387f9602299cb708a26cf04ffdfd23686a75"
os = "freebsd"

    [[gdk_pixbuf.download]]
    sha256 = "7d7b22f5cd43c18534d1a6bbe209f88b50404385fe12524c8548e89850d501b9"
    url = "https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/releases/download/gdk_pixbuf-v2.38.2+1/gdk_pixbuf.v2.38.2.x86_64-unknown-freebsd11.1.tar.gz"
